using System;
using System.Text.RegularExpressions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace NetStatWPF.Test
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var record = new NetStatDataRecord();
            //Rest of string from XML:
            #region IPv4 Statistics
            //" IPv4 StatisticsPackets Received = 18087305Received Header Errors = 0Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            var testData = " IPv4 StatisticsPackets Received = 18087305Received Header Errors = 0Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            var pattern = new Regex(@"IPv4 StatisticsPackets Received\D+(?'number'\d+)(?'rest'.*)");
            var match = pattern.Match(testData);
            record.IPv4Statistics.PacketsReceived = long.Parse(match.Groups["number"].Value);
            var rest = match.Groups["rest"].Value;

            //Rest of string from XML: "Received Header Errors = 0Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReceivedHeaderErrors = Extract64BitNumber(patternString: @"Received Header Errors\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReceivedAddressErrors = Extract64BitNumber(patternString: @"Received Address Errors\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.DatagramsForwarded = Extract64BitNumber(patternString: @"Datagrams Forwarded\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.UnknownProtocolsReceived = Extract64BitNumber(patternString: @"Unknown Protocols Received\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReceivedPacketsDiscarded = Extract64BitNumber(patternString: @"Received Packets Discarded\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(6422, record.IPv4Statistics.ReceivedPacketsDiscarded);
            //Rest of string from XML: "Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReceivedPacketsDelivered = Extract64BitNumber(patternString: @"Received Packets Delivered\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(9185993, record.IPv4Statistics.ReceivedPacketsDelivered);
            //Rest of string from XML: "Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.OutputRequests = Extract64BitNumber(patternString: @"Output Requests\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(14917140, record.IPv4Statistics.OutputRequests);
            //Rest of string from XML: "Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.RoutingDiscards = Extract64BitNumber(patternString: @"Routing Discards\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(0, record.IPv4Statistics.RoutingDiscards);
            //Rest of string from XML: "Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.DiscardedOutputPackets = Extract64BitNumber(patternString: @"Discarded Output Packets\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(276, record.IPv4Statistics.DiscardedOutputPackets);
            //Rest of string from XML: "Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.OutputPacketNoRoute = Extract64BitNumber(patternString: @"Output Packet No Route\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReassemblyRequired = Extract64BitNumber(patternString: @"Reassembly Required\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReassemblySuccessful = Extract64BitNumber(patternString: @"Reassembly Successful\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.ReassemblyFailures = Extract64BitNumber(patternString: @"Reassembly Failures\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.DatagramsSuccessfullyFragmented = Extract64BitNumber(patternString: @"Datagrams Successfully Fragmented\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(0, record.IPv4Statistics.DatagramsSuccessfullyFragmented);
            //Rest of string from XML: "Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.DatagramsFailingFragmentation = Extract64BitNumber(patternString: @"Datagrams Failing Fragmentation\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(0, record.IPv4Statistics.DatagramsFailingFragmentation);
            //Rest of string from XML: "Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv4Statistics.FragmentsCreated = Extract64BitNumber(patternString: @"Fragments Created\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(0, record.IPv4Statistics.FragmentsCreated);
            #endregion

            #region IPv6 Statistics
            //Rest of string from XML: "IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.PacketsReceived = Extract64BitNumber(patternString: @"Packets Received\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(5847, record.IPv6Statistics.PacketsReceived);
            //Rest of string from XML: "Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.ReceivedHeaderErrors = Extract64BitNumber(patternString: @"Received Header Errors\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            //Rest of string from XML: "Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.ReceivedAddressErrors = Extract64BitNumber(patternString: @"Received Address Errors\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(116, record.IPv6Statistics.ReceivedAddressErrors);
            //Rest of string from XML: "Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.DatagramsForwarded = Extract64BitNumber(patternString: @"Datagrams Forwarded\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(0, record.IPv6Statistics.DatagramsForwarded);

            //Rest of string from XML: "Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.UnknownProtocolsReceived = Extract64BitNumber(patternString: @"Unknown Protocols Received\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(0, record.IPv6Statistics.UnknownProtocolsReceived);

            //Rest of string from XML: "Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.ReceivedPacketsDiscarded = Extract64BitNumber(patternString: @"Received Packets Discarded\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(3121, record.IPv6Statistics.ReceivedPacketsDiscarded);

            //Rest of string from XML: "Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.ReceivedPacketsDelivered = Extract64BitNumber(patternString: @"Received Packets Delivered\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(8173, record.IPv6Statistics.ReceivedPacketsDelivered);

            //Rest of string from XML: "Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            record.IPv6Statistics.OutputRequests = Extract64BitNumber(patternString: @"Output Requests\D+(?'number'\d+)(?'rest'.*)", input: rest, out rest);
            Assert.AreEqual(7194, record.IPv6Statistics.OutputRequests);
            #endregion
        }
        Int64 Extract64BitNumber(string patternString, string input, out string rest)
        {
            var pattern = new Regex(patternString);
            var match = pattern.Match(input);
            var retVal = Int64.Parse(match.Groups["number"].Value);
            rest = match.Groups["rest"].Value;
            return retVal;
        }

        class NetStatDataRecord
        {
            internal NetStatDataRecord()
            {
                IPv4Statistics = new IPv4StatisticsClass();
                IPv6Statistics = new IPv6StatisticsClass();
            }
            internal class IPv4StatisticsClass
            {
                public Int64 PacketsReceived { get; internal set; }
                public Int64 ReceivedHeaderErrors { get; internal set; }
                public Int64 ReceivedAddressErrors { get; internal set; }
                public Int64 DatagramsForwarded { get; internal set; }
                public Int64 UnknownProtocolsReceived { get; internal set; }
                public Int64 ReceivedPacketsDiscarded { get; internal set; }
                public Int64 ReceivedPacketsDelivered { get; internal set; }
                public Int64 OutputRequests { get; internal set; }
                public Int64 RoutingDiscards { get; internal set; }
                public Int64 DiscardedOutputPackets { get; internal set; }
                public Int64 OutputPacketNoRoute { get; internal set; }
                public Int64 ReassemblyRequired { get; internal set; }
                public Int64 ReassemblySuccessful { get; internal set; }
                public Int64 ReassemblyFailures { get; internal set; }
                public Int64 DatagramsSuccessfullyFragmented { get; internal set; }
                public Int64 DatagramsFailingFragmentation { get; internal set; }
                public Int64 FragmentsCreated { get; internal set; }
            }

            internal class IPv6StatisticsClass
            {
                public Int64 PacketsReceived { get; internal set; }
                public Int64 ReceivedHeaderErrors { get; internal set; }
                public Int64 ReceivedAddressErrors { get; internal set; }
                public Int64 DatagramsForwarded { get; internal set; }
                public Int64 UnknownProtocolsReceived { get; internal set; }
                public Int64 ReceivedPacketsDiscarded { get; internal set; }
                public long ReceivedPacketsDelivered { get; internal set; }
                public long OutputRequests { get; internal set; }
            }
            public IPv4StatisticsClass IPv4Statistics { get; internal set; }
            public IPv6StatisticsClass IPv6Statistics { get; internal set; }
        }

    }
}
