using System;
using System.Text.RegularExpressions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace NetStatWPF.Test
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            //Rest of string from XML:
            //" IPv4 StatisticsPackets Received = 18087305Received Header Errors = 0Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            var testData = " IPv4 StatisticsPackets Received = 18087305Received Header Errors = 0Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            var pattern = new Regex(@"IPv4 StatisticsPackets Received\D+(?'number'\d+)(?'rest'.*)");
            var match = pattern.Match(testData);

            var ipV4Stats = match.Groups["number"].Value;
            var rest = match.Groups["rest"].Value;

            //Rest of string from XML: "Received Header Errors = 0Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            pattern = new Regex(@"Received Header Errors\D+(?'number'\d+)(?'rest'.*)");
            match = pattern.Match(rest);
            var rhErrors = match.Groups["number"].Value;
            rest = match.Groups["rest"].Value;

            //Rest of string from XML: "Received Address Errors = 35Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            pattern = new Regex(@"Received Address Errors\D+(?'number'\d+)(?'rest'.*)");
            match = pattern.Match(rest);
            var raErrors = match.Groups["number"].Value;
            rest = match.Groups["rest"].Value;

            //Rest of string from XML: "Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            pattern = new Regex(@"Datagrams Forwarded\D+(?'number'\d+)(?'rest'.*)");
            match = pattern.Match(rest);
            var datagramsForwarded = match.Groups["number"].Value;
            rest = match.Groups["rest"].Value;

            //Rest of string from XML: "Unknown Protocols Received = 0Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            pattern = new Regex(@"Unknown Protocols Received\D+(?'number'\d+)(?'rest'.*)");
            match = pattern.Match(rest);
            var unkProtoRcvd = match.Groups["number"].Value;
            rest = match.Groups["rest"].Value;

            //Rest of string from XML: "Received Packets Discarded = 6422Received Packets Delivered = 9185993Output Requests = 14917140Routing Discards = 0Discarded Output Packets = 276Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 IPv6 StatisticsPackets Received = 5847Received Header Errors = 0Received Address Errors = 116Datagrams Forwarded = 0Unknown Protocols Received = 0Received Packets Discarded = 3121Received Packets Delivered = 8173Output Requests = 7194Routing Discards = 0Discarded Output Packets = 0Output Packet No Route = 0Reassembly Required = 0Reassembly Successful = 0Reassembly Failures = 0Datagrams Successfully Fragmented = 0Datagrams Failing Fragmentation = 0Fragments Created = 0 ICMPv4 StatisticsReceived SentMessages 340 368Errors 0 0Destination Unreachable 340 368Time Exceeded 0 0Parameter Problems 0 0Source Quenches 0 0Redirects 0 0Echo Replies 0 0Echos 0 0Timestamps 0 0Timestamp Replies 0 0Address Masks 0 0Address Mask Replies 0 0Router Solicitations 0 0Router Advertisements 0 0 ICMPv6 StatisticsReceived SentMessages 214 21Errors 0 0Destination Unreachable 0 0Packet Too Big 0 0Time Exceeded 0 0Parameter Problems 0 0Echos 0 0Echo Replies 0 0MLD Queries 0 0MLD Reports 2 0MLD Dones 0 0Router Solicitations 0 9Router Advertisements 203 0Neighbor Solicitations 1 6Neighbor Advertisements 8 6Redirects 0 0Router Renumberings 0 0 TCP Statistics for IPv4Active Opens = 19796Passive Opens = 721Failed Connection Attempts = 14385Reset Connections = 863Current Connections = 37Segments Received = 9007968Segments Sent = 14458528Segments Retransmitted = 60816 TCP Statistics for IPv6Active Opens = 144Passive Opens = 19Failed Connection Attempts = 40Reset Connections = 0Current Connections = 0Segments Received = 2115Segments Sent = 1698Segments Retransmitted = 14 UDP Statistics for IPv4Datagrams Received = 287014No Ports = 6306Receive Errors = 6Datagrams Sent = 470359 UDP Statistics for IPv6Datagrams Received = 7511No Ports = 3121Receive Errors = 0Datagrams Sent = 5636 ";
            pattern = new Regex(@"Received Packets Discarded\D+(?'number'\d+)(?'rest'.*)");
            match = pattern.Match(rest);
            var recPckDisc = match.Groups["number"].Value;
            rest = match.Groups["rest"].Value;



        }
    }
}
